### ISSUE TITLE
using the human cell landscape

### ISSUE THREAD

**Issue by kguion1** [Drizzle-Zhang/scMAGIC#11]
Excited to start using this package!

I have single cell dataset from human liver and am trying to label each cell as a specific cell type. I found your paper and recommendation to use the human cell landscape. I tried navigating through their website and couldn't find where to download an appropriate reference dataset to use with your package. Could you provide step by step instructions for this?

Thank you!

**Comment by Drizzle-Zhang** [comment]
You can annotate your single cell dataset using HCL according to the section 3 of  README. (https://github.com/Drizzle-Zhang/scMAGIC#%E2%85%B2-reference-free-annotation)

**Comment by kguion1** [comment]
okay, thank you for your quick response! Should the input single cell be the SCTransform-ed counts or the raw counts?

THank you!

**Comment by Drizzle-Zhang** [comment]
I used to input the raw counts to test scMAGIC, but you can also try to input the SCTransform-ed counts.

**Comment by kguion1** [comment]
thank you!
