### ISSUE TITLE
Too large a percentage of total singular values

### ISSUE THREAD

**Issue by ViriatoII** [Drizzle-Zhang/scMAGIC#2]
Hi,

I get this message:

>  Warning in irlba(A = t(x = object), nv = npcs, ...) :
 You're computing too large a percentage of total singular values, use a standard svd instead.
 Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: more cluster centers than distinct data points.

Does scMagic not like my data? I only have 100 genes, is that the problem?

Kind regards,
Ricardo

**Comment by Drizzle-Zhang** [comment]
The gene number may be too small. In general, a single cell RNA-seq matrix contains at least thousands of genes.
