### ISSUE TITLE
Error in exp_ref_mat when using scMAGIC to annotate cell type

### ISSUE THREAD

**Issue by ivy-yuan** [Drizzle-Zhang/scMAGIC#3]
I got an error when I tried to use this tool to annotate my scRNA-seq data. The reference data used was a normalized count data frame  of  25,032 genes  and 10,174 cells. The target data used was a normalized count data frame  of   27,581 genes and 5105 cells. Here are the details of the code and the error I encountered. How could I fix this error?

`> output.scMAGIC <- scMAGIC(expr_data, liver_ref, label_ref, atlas = 'HCA')`
`[1] "Sum single cell counts matrix:"`
`Error in exp_ref_mat[gene_over, ] : incorrect number of dimensions`

**Comment by Drizzle-Zhang** [comment]
The parameter “atlas” should be "HCL"
