### ISSUE TITLE
Error “subscript out of bounds”

### ISSUE THREAD

**Issue by xqs-time** [Drizzle-Zhang/scMAGIC#4]
hello，This is my code and error message 
```
res = scMAGIC(b, a, exp_ref_label=label, atlas='HCL', num_threads = 2)
[1] "Build local reference"
Error in exp_sc_mat[total_genes, sel_cols] : subscript out of bounds
```
Can you tell me how to solve it? Thanks.

**Comment by xqs-time** [comment]
I then found that it was caused by NA in the result of ".find_markers"

**Comment by Drizzle-Zhang** [comment]
Thanks! The bug has been fixed. Please reinstall scMAGIC and try again.
