### ISSUE TITLE
Error reproducing tutorial sample

### ISSUE THREAD

**Issue by guerrerosimonl** [Drizzle-Zhang/scMAGIC#9]
I'm trying to reproduce your scMAGIC_Seurat function with the datasets from your tutorial (Tasic.Rdata and Campbell_2k.RData), using exactly the same steps.

After [1] "First-round annotation:" message, I get the error: 

`Error in t.default(exp_ref_mat.cell) : argument is not a matrix`

**Comment by Drizzle-Zhang** [comment]
This error may be caused by the sparse matrix operations, and I have fixed it. Please reinstall scMAGIC and try again.

**Comment by guerrerosimonl** [comment]
Solved! Thanks :)
